[database]
db_type = ""
host = ""
port = 0
username = ""
password = ""
db_name = ""

[sidecar]
name = "binaries/goservices"
port = 9005

[ui]
mode = "dark"
toast_rich_colors = true
date_format = "DD-MM-YYYY"
