CREATE TABLE FINANCIAL_YEARS (
    id INTEGER AUTO_INCREMENT,
    financial_year VARCHAR(10) NOT NULL,
    CONSTRAINT pk_fy_id PRIMARY KEY (id)
);

INSERT INTO FINANCIAL_YEARS (financial_year) VALUES ("2023-24"), ("2024-25");