CREATE TABLE vendor_details (
    vendor_id INTEGER AUTO_INCREMENT,
    vendor_name VARCHAR(100) NOT NULL,
    address1 VARCHAR(100),
    address2 VARCHAR(100),
    address3 VARCHAR(100),
    address4 VARCHAR(100),
    state_id INTEGER NOT NULL,
    pin_code VARCHAR(100),
    phone_number VARCHAR(100),
    email_id VARCHAR(100),
    vgstin VARCHAR(100),
    fssai VARCHAR(100),
    bank_name VARCHAR(100),
    branch_name VARCHAR(100),
    account_number VARCHAR(100),
    ifsc_code VARCHAR(100),
    account_holder_name VARCHAR(100),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified_date TIMESTAMP,
    is_deleted BOOL DEFAULT FALSE,
    CONSTRAINT pk_vendor_id PRIMARY KEY (vendor_id),
    CONSTRAINT fk_vendor_details_state_list FOREIGN KEY (state_id) REFERENCES state_list(id)
)